# Generated by Django 4.1.7 on 2023-02-22 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closing_date',
            field=models.DateTimeField(default=datetime.date(2023, 2, 22)),
            preserve_default=False,
        ),
    ]
